/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'userID' : IDL.Principal,
});

export const idlService = IDL.Service({
  'clearMessages' : IDL.Func([], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getFamilyMemberList' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'userID' : IDL.Principal,
  });
  
  return IDL.Service({
    'clearMessages' : IDL.Func([], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getFamilyMemberList' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };